### ISSUE TITLE
D'où viennent les sprites du bestiaire ?

### ISSUE THREAD

**Issue by Kell0x** [Dipess/naheulbeuk#1]
Hello,

Je voudrais savoir si tu avais utilisé un outil pour générer les sprites du bestiaire, j'adore ton système de jeu, et je prévois de m'en servir pour ma campagne, mais je voudrais que le style des personnages colle avec ceux des rencontres :)

**Comment by Dipess** [comment]
Hello ! 
Déjà merci pour ton retour, ça me fait bien plaisir !
Avant de te répondre, je ne sais pas si tu as trouvé le système via le discord La Fonderie, mais si ce n’est pas le cas je t’encourage à aller dessus pour les news.
Par exemple, la dernière mise à jour casse un certain nombre de choses et il y a les explications de ce qu’il faut faire avant de procéder à cette mise à jour.
Ensuite pour te répondre, les tokens sont tous issus du site : https://tools.2minutetabletop.com/token-editor/
Dessus, tu as pas mal de choix et tu peux personnaliser les couleurs, ombres etc…
Mais pour info j’ai déjà mis un bon nombre de tokens dans le système, trouvables dans : Données de l’utilisateur puis systems/naheulbeuk/assets/from-2minutetabletop.com-token/
Voilà voilà, bonne partie !
